# Generated by Django 4.1.7 on 2023-03-08 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersprofile',
            name='avatar',
            field=models.ImageField(default='default.jpg', upload_to='avatar_img'),
        ),
    ]
