# Generated by Django 4.1.7 on 2023-03-06 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatApp', '0002_usersprofile_alter_messages_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersprofile',
            name='avatar',
            field=models.ImageField(default='/media/default.jpg', upload_to='media/avatar_img'),
        ),
    ]
