# Generated by Django 4.1.7 on 2023-03-01 08:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatApp', '0003_alter_room_members'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chat_User',
            new_name='Chat_Users',
        ),
        migrations.RenameModel(
            old_name='Message',
            new_name='Messages',
        ),
        migrations.RenameModel(
            old_name='Room',
            new_name='Rooms',
        ),
    ]
