# Generated by Django 4.1.7 on 2023-03-07 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatApp', '0005_alter_usersprofile_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomsMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatRoom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatApp.rooms')),
                ('userProfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatApp.usersprofile')),
            ],
        ),
        migrations.AlterField(
            model_name='rooms',
            name='members',
            field=models.ManyToManyField(blank=True, through='chatApp.RoomsMembers', to='chatApp.usersprofile'),
        ),
    ]
